general.import = [
  "~/.config/alacritty/theme.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic= { family = "JetBrains Mono", style = "Italic" }
size = 10.0

[env]
TERM = "xterm-256color"

[terminal]
shell= "/bin/zsh"
