"""Contract checks for generated theme template and imported palette headers."""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PALETTES = (
    "osaka-jade",
    "catppuccin",
    "catppuccin-latte",
    "ethereal",
    "flexoki-light",
    "ristretto",
    "nord",
    "rose-pine",
    "everforest",
    "gruvbox",
    "kanagawa",
)
CANONICAL_IMPORT = "-- Imported from Omarchy; missing roles come from _defaults.lua."


def _lua_code(line: str) -> str:
    """Return Lua code outside quoted strings and line comments."""
    result: list[str] = []
    quote: str | None = None
    escaped = False
    index = 0
    while index < len(line):
        char = line[index]
        if quote:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
        elif char in "'\"":
            quote = char
        elif line[index : index + 2] == "--":
            break
        else:
            result.append(char)
        index += 1
    return "".join(result)


def _assert_depth_indentation(source: str) -> None:
    depth = 0
    for line_number, line in enumerate(source.splitlines()[1:], start=2):
        stripped = line.strip()
        if not stripped:
            continue
        code = _lua_code(stripped)
        closes = len(code) - len(code.lstrip("}"))
        expected_depth = max(0, depth - closes)
        assert line == "  " * expected_depth + stripped, (
            f"line {line_number} should be indented {expected_depth * 2} spaces"
        )
        depth += code.count("{") - code.count("}")
        assert depth >= 0, f"unbalanced table close at line {line_number}"
    assert depth == 0, "unclosed table constructor"


def test_generated_template_headers_use_native_comment_syntax() -> None:
    cases = {
        "alacritty.toml.tpl": (
            "# Generated by themectl from {{name}}. Do not edit; change the palette or",
            "# templates/alacritty.toml.tpl in ~/.dotfiles/themes instead.",
        ),
        "env.sh.tpl": (
            "# Generated by themectl from {{name}}. Do not edit; change the palette or",
            "# templates/env.sh.tpl in ~/.dotfiles/themes instead.",
        ),
        "herdr-theme.toml.tpl": (
            "# Generated by themectl from {{name}}. Do not edit; change the palette or",
            "# templates/herdr-theme.toml.tpl in ~/.dotfiles/themes instead.",
        ),
        "rofi-config.rasi.tpl": (
            "/* Generated by themectl from {{name}}. Do not edit; change the palette or",
            "   templates/rofi-config.rasi.tpl in ~/.dotfiles/themes instead. */",
        ),
        "waybar-config.jsonc.base.tpl": (
            "// Generated by themectl from {{name}}; plugin wiring is assembled by pluginctl.",
            "// Do not edit; change templates/waybar-config.jsonc.base.tpl or plugin sources instead.",
        ),
    }
    for filename, required in cases.items():
        lines = (ROOT / "themes/templates" / filename).read_text().splitlines()
        header_start = 1 if lines[0].startswith("#!") else 0
        assert tuple(lines[header_start : header_start + len(required)]) == required
        if filename.endswith(".sh.tpl"):
            assert not lines[0].startswith("#!") or lines[1].startswith("#")


def test_imported_palettes_have_canonical_headers_valid_lua_and_depth_indentation() -> None:
    lua = shutil.which("lua")
    luac = shutil.which("luac")
    assert lua and luac, "Lua and luac are required for palette validation"

    with tempfile.TemporaryDirectory(prefix="theme-headers-") as temporary:
        temp = Path(temporary)
        home = temp / "home"
        home.mkdir()
        bin_dir = temp / "bin"
        bin_dir.mkdir()
        for executable in (lua, luac):
            link = bin_dir / Path(executable).name
            link.symlink_to(executable)
        env = {"HOME": str(home), "PATH": str(bin_dir), "LC_ALL": "C"}

        fixtures: list[Path] = []
        for palette in PALETTES:
            source = (ROOT / f"themes/palettes/{palette}.lua").read_text()
            assert source.splitlines()[0] == CANONICAL_IMPORT
            _assert_depth_indentation(source)
            fixture = temp / f"{palette}.lua"
            fixture.write_text(source)
            fixtures.append(fixture)

        subprocess.run(
            [luac, "-p", *map(str, fixtures)], check=True, env=env, timeout=10
        )
        harness = temp / "validate-palettes.lua"
        harness.write_text(
            """local palettes = {}
for index = 1, #arg do
  local palette = dofile(arg[index])
  assert(type(palette) == "table")
  palettes[palette.name] = palette
end
assert(palettes["osaka-jade"].yellow == "#459451")
assert(palettes["osaka-jade"].ansi.normal.yellow == "#459451")
assert(palettes.kanagawa.accent == "#dcd7ba")
assert(palettes.kanagawa.fg == "#dcd7ba")
assert(palettes.catppuccin.ansi.normal.black == "#45475a")
assert(palettes.catppuccin.ansi.bright.black == "#585b70")
"""
        )
        subprocess.run(
            [lua, str(harness), *map(str, fixtures)],
            check=True,
            env=env,
            timeout=10,
        )
