-- Generated by themectl from {{name}}. Do not edit; change the palette or
-- templates/awesome-colors.lua.tpl in ~/.dotfiles/themes instead.
return {
    bg = "{{bg}}",
    fg = "{{fg}}",
    accent = "{{accent}}",
    surface = "{{surface}}",
    bg_dark = "{{bg_dark}}",
    muted = "{{muted}}",
    bar_bg = "{{awesome.bar_bg}}",
    border_normal = "{{awesome.border_normal}}",
    border_focus = "{{awesome.border_focus}}",
    titlebar_fg_focus = "{{awesome.titlebar_fg_focus}}",
    widget_a = "{{awesome.widget_a}}",
    widget_b = "{{awesome.widget_b}}",
    widget_c = "{{awesome.widget_c}}",
}
