# Generated by themectl from {{name}}. Do not edit; change the palette or
# templates/env.sh.tpl in ~/.dotfiles/themes instead.
THEME_NAME="{{name}}"
THEME_BG="{{bg}}"
THEME_RNMUI="{{rnmui}}"
THEME_NVIM_COLORSCHEME="{{nvim.colorscheme}}"
THEME_NVIM_FLAVOUR="{{nvim.flavour}}"
