# Generated by themectl from {{name}}. Do not edit; change the palette or
# templates/ghostty-theme.tpl in ~/.dotfiles/themes instead.
background = {{bg}}
foreground = {{fg}}
cursor-color = {{cursor}}
cursor-text = {{bg}}
selection-background = {{selection}}
selection-foreground = {{bg}}
palette = 0={{ansi.normal.black}}
palette = 1={{ansi.normal.red}}
palette = 2={{ansi.normal.green}}
palette = 3={{ansi.normal.yellow}}
palette = 4={{ansi.normal.blue}}
palette = 5={{ansi.normal.magenta}}
palette = 6={{ansi.normal.cyan}}
palette = 7={{ansi.normal.white}}
palette = 8={{ansi.bright.black}}
palette = 9={{ansi.bright.red}}
palette = 10={{ansi.bright.green}}
palette = 11={{ansi.bright.yellow}}
palette = 12={{ansi.bright.blue}}
palette = 13={{ansi.bright.magenta}}
palette = 14={{ansi.bright.cyan}}
palette = 15={{ansi.bright.white}}
