/* Generated by themectl from {{name}}. Do not edit; change the palette or
   templates/gtk3.css.tpl in ~/.dotfiles/themes instead. */
@define-color theme_bg_color {{bg}};
@define-color theme_fg_color {{fg}};
@define-color theme_base_color {{bg}};
@define-color theme_text_color {{fg}};
@define-color theme_selected_bg_color {{accent}};
@define-color theme_selected_fg_color {{bg}};
@define-color theme_unfocused_bg_color {{bg}};
@define-color theme_unfocused_fg_color {{muted}};
@define-color theme_unfocused_base_color {{bg}};
@define-color theme_unfocused_text_color {{muted}};
@define-color theme_unfocused_selected_bg_color {{surface_alt}};
@define-color theme_unfocused_selected_fg_color {{fg}};
@define-color insensitive_bg_color {{surface}};
@define-color insensitive_fg_color {{fg_dim}};
@define-color insensitive_base_color {{bg}};
@define-color borders {{surface_alt}};
@define-color unfocused_borders {{surface}};
@define-color warning_color {{yellow}};
@define-color error_color {{red}};
@define-color success_color {{green}};
