# Generated by themectl from {{name}}. Do not edit; change the palette or
# templates/gtk3-settings.ini.tpl in ~/.dotfiles/themes instead.
# The theme follows the palette's variant, so a light palette gets light
# widgets; gtk3.css then recolors either one with the palette.
[Settings]
gtk-theme-name={{gtk3_theme}}
gtk-application-prefer-dark-theme={{gtk_prefer_dark}}
gtk-font-name=JetBrainsMono Nerd Font 10
