/* Generated by themectl from {{name}}. Do not edit; change the palette or
   templates/gtk3.css.tpl in ~/.dotfiles/themes instead.

   Stock Adwaita compiles its GTK3 colors in, so redefining them here changes
   nothing. adw-gtk3, the GTK3 theme gtk3-settings.ini selects, draws every
   widget from libadwaita's named colors instead, so this block recolors
   PCManFM and every other GTK3 app. Keep it in step with gtk4.css.tpl. */
@define-color accent_color {{accent}};
@define-color accent_bg_color {{accent}};
@define-color accent_fg_color {{bg}};
@define-color destructive_color {{red}};
@define-color destructive_bg_color {{red}};
@define-color destructive_fg_color {{bg}};
@define-color success_color {{green}};
@define-color warning_color {{yellow}};
@define-color error_color {{red}};
@define-color window_bg_color {{bg}};
@define-color window_fg_color {{fg}};
@define-color view_bg_color {{bg}};
@define-color view_fg_color {{fg}};
@define-color headerbar_bg_color {{bg_alt}};
@define-color headerbar_fg_color {{fg}};
@define-color headerbar_border_color {{surface}};
@define-color card_bg_color {{surface}};
@define-color card_fg_color {{fg}};
@define-color dialog_bg_color {{bg}};
@define-color dialog_fg_color {{fg}};
@define-color popover_bg_color {{surface}};
@define-color popover_fg_color {{fg}};
@define-color sidebar_bg_color {{bg_alt}};
@define-color sidebar_fg_color {{fg}};
@define-color sidebar_backdrop_color {{bg_alt}};
@define-color sidebar_border_color {{surface}};

/* The pre-libadwaita names, for apps whose own CSS still asks for them. */
@define-color theme_bg_color {{bg}};
@define-color theme_fg_color {{fg}};
@define-color theme_base_color {{bg}};
@define-color theme_text_color {{fg}};
@define-color theme_selected_bg_color {{accent}};
@define-color theme_selected_fg_color {{bg}};
@define-color theme_unfocused_bg_color {{bg}};
@define-color theme_unfocused_fg_color {{muted}};
@define-color theme_unfocused_base_color {{bg}};
@define-color theme_unfocused_text_color {{muted}};
@define-color theme_unfocused_selected_bg_color {{surface_alt}};
@define-color theme_unfocused_selected_fg_color {{fg}};
@define-color insensitive_bg_color {{surface}};
@define-color insensitive_fg_color {{fg_dim}};
@define-color insensitive_base_color {{bg}};
@define-color borders {{surface_alt}};
@define-color unfocused_borders {{surface}};
