/* Generated by themectl from {{name}}. Do not edit; change the palette or
   templates/gtk4.css.tpl in ~/.dotfiles/themes instead. */
@define-color accent_color {{accent}};
@define-color accent_bg_color {{accent}};
@define-color accent_fg_color {{bg}};
@define-color destructive_color {{red}};
@define-color destructive_bg_color {{red}};
@define-color destructive_fg_color {{bg}};
@define-color success_color {{green}};
@define-color warning_color {{yellow}};
@define-color error_color {{red}};
@define-color window_bg_color {{bg}};
@define-color window_fg_color {{fg}};
@define-color view_bg_color {{bg}};
@define-color view_fg_color {{fg}};
@define-color headerbar_bg_color {{bg_alt}};
@define-color headerbar_fg_color {{fg}};
@define-color headerbar_border_color {{surface}};
@define-color card_bg_color {{surface}};
@define-color card_fg_color {{fg}};
@define-color dialog_bg_color {{bg}};
@define-color dialog_fg_color {{fg}};
@define-color popover_bg_color {{surface}};
@define-color popover_fg_color {{fg}};
@define-color sidebar_bg_color {{bg_alt}};
@define-color sidebar_fg_color {{fg}};
@define-color sidebar_backdrop_color {{bg_alt}};
@define-color sidebar_border_color {{surface}};
