# Generated by themectl from {{name}}. Do not edit; change the palette or
# templates/herdr-theme.toml.tpl in ~/.dotfiles/themes instead.
[theme]
name = "{{herdr_base}}"

[theme.custom]
accent = "{{accent}}"
surface0 = "{{surface}}"
surface1 = "{{surface_alt}}"
surface_dim = "{{bg_alt}}"
overlay0 = "{{overlay}}"
overlay1 = "{{fg_dim}}"
text = "{{fg}}"
subtext0 = "{{muted}}"
mauve = "{{mauve}}"
green = "{{green}}"
yellow = "{{yellow}}"
red = "{{red}}"
blue = "{{blue}}"
teal = "{{cyan}}"
peach = "{{orange}}"
