# Generated by themectl from {{name}}. Do not edit; change the palette or
# templates/hypr-theme.conf.tpl in ~/.dotfiles/themes instead.
$active_border = {{accent|rgba}}
$inactive_border = {{accent_alt|rgba}}

# hyprlock
$lock_bg = {{bg|rgba}}
$lock_fg = {{fg|rgba}}
$lock_inner = {{surface|rgba}}
$lock_outer = {{accent|rgba}}
$lock_check = {{accent_alt|rgba}}
$lock_fail = {{red|rgba}}
