-- Generated by themectl from {{name}}. Do not edit; change the palette or
-- templates/hypr-theme.lua.tpl in ~/.dotfiles/themes instead.
return {
    active_border = "{{accent|rgba}}",
    inactive_border = "{{accent_alt|rgba}}",
}
