/* Generated by themectl from {{name}}. Do not edit; change the palette or
   templates/lightdm-gtk-greeter.css.tpl in ~/.dotfiles/themes instead.

   The login screen's GTK theme. themectl-greeter-sync copies it into
   /usr/share/themes/themectl-greeter when the greeter starts, and refuses a
   theme that loads files or stylesheets other than GTK's built-in Adwaita. */
@import url("resource:///org/gtk/libgtk/theme/Adwaita/{{adwaita_css}}");

@define-color g_bg {{bg}};
@define-color g_bg_alt {{bg_alt}};
@define-color g_surface {{surface}};
@define-color g_surface_alt {{surface_alt}};
@define-color g_fg {{fg}};
@define-color g_fg_dim {{fg_dim}};
@define-color g_accent {{accent}};
@define-color g_red {{red}};

* {
  outline-color: alpha(@g_accent, 0.6);
}

/* The panel along the top: host, clock, session, power. */
#panel_window {
  background-color: {{bg_dark|css:0.85}};
  color: @g_fg;
  border-bottom: 1px solid alpha(@g_surface_alt, 0.6);
}

#panel_window menubar {
  background: transparent;
  box-shadow: none;
  padding: 2px 6px;
}

#panel_window menubar > menuitem {
  color: @g_fg;
  padding: 4px 10px;
  border-radius: 6px;
}

#panel_window menubar > menuitem:hover {
  background-color: @g_surface;
  color: @g_accent;
}

#panel_window menubar > menuitem:disabled {
  color: @g_fg_dim;
}

#clock_menuitem {
  font-weight: bold;
}

/* Drop-down menus from the panel and the user list. */
menu,
.menu,
.context-menu {
  background-color: @g_bg_alt;
  color: @g_fg;
  border: 1px solid @g_surface_alt;
  padding: 4px;
}

menu menuitem {
  padding: 6px 12px;
  border-radius: 4px;
}

menu menuitem:hover {
  background-color: @g_accent;
  color: @g_bg;
}

menu menuitem:disabled {
  color: @g_fg_dim;
}

/* The login card and the shutdown/restart confirmation share one look. */
#login_window,
#power_window {
  background-color: {{bg|css:0.92}};
  color: @g_fg;
  border: 1px solid @g_surface_alt;
  border-top: 3px solid @g_accent;
  border-radius: 12px;
  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.45);
}

#content_frame,
#power_content_frame {
  padding: 24px 32px 12px 32px;
}

#buttonbox_frame,
#power_buttonbox_frame {
  padding: 8px 32px 24px 32px;
  background: transparent;
  border: none;
}

#user_image {
  padding: 4px;
}

#user_image_border {
  background: transparent;
  box-shadow: none;
}

/* Styled like the other buttons below, just with the name larger. */
#user_combobox button {
  font-size: 16pt;
}

#user_combobox arrow {
  color: @g_fg_dim;
}

#power_title {
  font-size: 14pt;
  font-weight: bold;
  color: @g_accent;
}

#login_window entry,
#power_window entry {
  min-height: 34px;
  padding: 0 10px;
  background-color: @g_surface;
  background-image: none;
  color: @g_fg;
  caret-color: @g_accent;
  border: 1px solid @g_surface_alt;
  border-radius: 8px;
  box-shadow: none;
}

#login_window entry:focus {
  border-color: @g_accent;
  box-shadow: inset 0 0 0 1px @g_accent;
}

#login_window entry selection {
  background-color: @g_accent;
  color: @g_bg;
}

#login_window entry placeholder {
  color: @g_fg_dim;
}

#login_window button,
#power_window button {
  min-height: 32px;
  padding: 0 18px;
  background-color: @g_surface;
  background-image: none;
  color: @g_fg;
  border: 1px solid @g_surface_alt;
  border-radius: 8px;
  box-shadow: none;
  text-shadow: none;
}

#login_window button:hover,
#power_window button:hover {
  background-color: @g_surface_alt;
}

#login_button,
#power_ok_button {
  font-weight: bold;
}

#login_window #login_button {
  background-color: @g_accent;
  border-color: @g_accent;
  color: @g_bg;
}

#login_window #login_button:hover {
  background-color: shade(@g_accent, 1.1);
}

/* Shutdown and restart are destructive; tint the confirm button red. */
#power_window #power_ok_button {
  background-color: @g_red;
  border-color: @g_red;
  color: @g_bg;
}

#power_window #power_ok_button:hover {
  background-color: shade(@g_red, 1.1);
}

/* Wrong password and other PAM messages. */
#greeter_infobar,
#greeter_infobar revealer > box {
  background-color: {{red|css:0.18}};
  background-image: none;
  color: @g_red;
  border: none;
  border-radius: 8px;
  font-weight: bold;
}

#message_label {
  color: @g_red;
}
