# Generated by themectl from {{name}}. Do not edit; change the palette or
# templates/p10k-theme.zsh.tpl in ~/.dotfiles/themes instead.
# Only the segments that use fixed 256-color numbers are overridden; the rest
# use ANSI colors 0-7, which already follow the terminal palette.
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='{{bg_dark}}'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='{{fg}}'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='{{fg_subtle}}'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='{{fg}}'
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='{{ansi.bright.black}}'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND='{{overlay}}'
typeset -g POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='{{ansi.bright.black}}'
