; Generated by themectl from {{name}}. Do not edit; change
; templates/qt6ct.conf.tpl in ~/.dotfiles/themes instead.
;
; qt6ct themes Qt6 apps (QT_QPA_PLATFORMTHEME=qt6ct): Fusion, recolored by
; the palette in qt6ct-colors.conf. File dialogs are GTK's, so they share
; the GTK theme and bookmarks. The font matches gtk3-settings.ini, quoted
; because QSettings would otherwise split it into a list at the commas.
[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=~/.config/qt6ct/colors/themectl.conf
standard_dialogs=gtk3

[Fonts]
general="JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
fixed="JetBrainsMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
