; Generated by themectl from {{name}}. Do not edit; change the palette or
; templates/qt6ct-colors.conf.tpl in ~/.dotfiles/themes instead.
;
; The Qt palette qt6ct applies to every Qt6 app, drawn from the same keys as
; gtk3.css so Qt and GTK windows match. One color per QPalette role, in order:
;   WindowText, Button, Light, Midlight, Dark, Mid, Text, BrightText,
;   ButtonText, Base, Window, Shadow, Highlight, HighlightedText, Link,
;   LinkVisited, AlternateBase, NoRole, ToolTipBase, ToolTipText,
;   PlaceholderText
; qt6ct fills in Accent (Qt 6.6+) from Highlight.
; Inactive windows show their selection like GTK3's unfocused one; disabled
; widgets dim their text.
[ColorScheme]
active_colors={{fg}}, {{surface}}, {{surface_alt}}, {{surface_alt}}, {{bg_dark}}, {{surface_alt}}, {{fg}}, {{fg}}, {{fg}}, {{bg}}, {{bg}}, {{bg_dark}}, {{accent}}, {{bg}}, {{accent}}, {{magenta}}, {{bg_alt}}, {{bg}}, {{surface}}, {{fg}}, {{fg_dim}}
inactive_colors={{fg}}, {{surface}}, {{surface_alt}}, {{surface_alt}}, {{bg_dark}}, {{surface_alt}}, {{fg}}, {{fg}}, {{fg}}, {{bg}}, {{bg}}, {{bg_dark}}, {{surface_alt}}, {{fg}}, {{accent}}, {{magenta}}, {{bg_alt}}, {{bg}}, {{surface}}, {{fg}}, {{fg_dim}}
disabled_colors={{fg_dim}}, {{surface}}, {{surface_alt}}, {{surface_alt}}, {{bg_dark}}, {{surface_alt}}, {{fg_dim}}, {{fg}}, {{fg_dim}}, {{bg}}, {{bg}}, {{bg_dark}}, {{accent}}, {{fg_dim}}, {{accent}}, {{magenta}}, {{bg_alt}}, {{bg}}, {{surface}}, {{fg}}, {{fg_dim}}
