/* Generated by themectl from {{name}}. Do not edit; change the palette or
   templates/swaync-colors.css.tpl in ~/.dotfiles/themes instead. */
@define-color base     {{bg}};
@define-color surface0 {{surface}};
@define-color surface1 {{surface_alt}};
@define-color surface2 {{ansi.bright.black}};
@define-color text     {{fg}};
@define-color subtext  {{muted}};
@define-color accent   {{accent}};
@define-color cyan     {{accent_alt}};
@define-color red      {{red}};
