# Generated by themectl from {{name}}. Do not edit; change the palette or
# templates/tmux-colors.conf.tpl in ~/.dotfiles/themes instead.
# config/tmux/theme.conf reads these through #{@thm_*}, so sourcing this file
# alone recolours every running session.
set -g @thm_bg '{{bg_alt}}'
set -g @thm_fg '{{fg}}'
set -g @thm_dim '{{fg_dim}}'
set -g @thm_surface '{{surface}}'
set -g @thm_surface_alt '{{surface_alt}}'
set -g @thm_accent '{{accent}}'
set -g @thm_on_accent '{{on_accent}}'
set -g @thm_accent_alt '{{accent_alt}}'
set -g @thm_yellow '{{yellow}}'
set -g @thm_red '{{red}}'
