/* Generated by themectl from {{name}}. Do not edit; change the palette or
   templates/waybar-colors.css.tpl in ~/.dotfiles/themes instead. */
@define-color bg {{bg}};
@define-color bg_alt {{bg_alt}};
@define-color surface {{surface}};
@define-color surface_alt {{surface_alt}};
@define-color fg {{fg}};
@define-color muted {{muted}};
@define-color dim {{ansi.bright.black}};
@define-color accent {{accent}};
@define-color accent_alt {{accent_alt}};
@define-color red {{red}};
@define-color yellow {{yellow}};
@define-color green {{green}};
