general {
    gaps_in = 4
    gaps_out = 4
    border_size = 0
    col.active_border = rgba(fab387ff)
    col.inactive_border = rgba(89dcebff)
    layout = dwindle
    allow_tearing = false
}

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = true
        size = 3
        passes = 2
    }
}

animations {
    enabled = true
    bezier = easeOut, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 4, easeOut
    animation = windowsOut, 1, 4, easeOut, popin 80%
    animation = border, 1, 4, default
    animation = fade, 1, 4, default
    animation = workspaces, 0, 4, easeOut
}

dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = true
    smart_resizing = true
}

master {
    new_status = master
    mfact = 0.50
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
    focus_on_activate = true
}

xwayland {
    force_zero_scaling = true
}
