-- Hyprland 0.55+ entry point. AwesomeWM remains the independent X11 session.

require("./lua/environment")
require("./lua/monitors")
require("./lua/input")
require("./lua/appearance")
require("./lua/rules")
require("./lua/autostart")
require("./lua/bindings")
require("./lua/plugins") -- generated by plugins/pluginctl; always exists, may be empty
