--[[

     Powerarrow Awesome WM theme
     github.com/lcpz

--]]

local c = require("themes.powerarrow.colors") -- generated by themectl
local gears = require("gears")
local gfs = require("gears.filesystem")
local lain = require("lain")
local awful = require("awful")
local naughty = require("naughty")
local wibox = require("wibox")
local dpi = require("beautiful.xresources").apply_dpi
local logout = require("awesome-wm-widgets.logout-widget.logout")
local power_mode = require("awesome-wm-widgets.power-mode-widget.power-mode")
local string, os, screen = string, os, screen
local my_table = awful.util.table or gears.table -- 4.{0,1} compatibility

local theme = {}
theme.bgDir = os.getenv("THEME_BG_DIR") or os.getenv("HOME") .. "/.backgrounds"
theme.dir = gfs.get_configuration_dir() .. "themes/powerarrow"
local default_theme_dir = gfs.get_themes_dir() .. "default/"
theme.wallpaper = theme.bgDir .. "/cosmo.png"
theme.wallpaperUltrawide = theme.bgDir .. "/arch_wide_bluish.png"

function theme.wallpaper_for(s)
	if s.geometry.width == 3440 and s.geometry.height == 1440 then
		return theme.wallpaperUltrawide
	end
	return theme.wallpaper
end

theme.font = "JetBrains Mono Nerd Font 10"

theme.fg_normal = c.fg -- Font Color
theme.bg_normal = c.bg

theme.fg_focus = "#ffffff"
theme.bg_focus = c.bar_bg -- Bars BG Color

theme.fg_urgent = "#aaaaaa"
theme.bg_urgent = c.accent

theme.popup_bg = c.surface
theme.popup_fg = theme.fg_normal
theme.popup_shape = function(cr, width, height)
	gears.shape.rounded_rect(cr, width, height, dpi(8))
end

theme.tooltip_bg = theme.popup_bg
theme.tooltip_fg = theme.popup_fg
theme.tooltip_border_width = 0
theme.tooltip_shape = theme.popup_shape

theme.notification_bg = theme.popup_bg
theme.notification_fg = theme.popup_fg
theme.notification_border_width = 0
theme.notification_shape = theme.popup_shape
theme.notification_margin = dpi(8)

-- Keep all top-bar notifications aligned below the bar with consistent spacing.
naughty.config.padding = dpi(8)
naughty.config.spacing = dpi(4)
naughty.config.defaults.position = "top_right"
naughty.config.defaults.margin = theme.notification_margin
naughty.config.presets.critical = {
	bg = theme.popup_bg,
	fg = theme.popup_fg,
	border_width = 0,
	shape = theme.popup_shape,
	margin = theme.notification_margin,
	position = "top_right",
	timeout = 0,
}
naughty.config.notify_callback = function(args)
	args.border_width = 0
	args.border_color = "#00000000"
	args.shape = theme.popup_shape
	return args
end

theme.taglist_fg_focus = c.accent
theme.taglist_bg_focus = "#00000000"

theme.tasklist_bg_focus = "#00000000"
theme.tasklist_fg_focus = c.accent

--theme.tasklist_bg_normal                        = "#333333"
--theme.tasklist_fg_normal                        = "#999999"

theme.border_width = dpi(0)
theme.border_normal = c.border_normal
theme.border_focus = c.border_focus
theme.border_marked = c.border_normal

theme.titlebar_fg_focus = c.titlebar_fg_focus
theme.titlebar_bg_focus = c.surface
theme.titlebar_bg_normal = c.bg_dark
theme.titlebar_fg_normal = c.muted

theme.menu_height = dpi(16)
theme.menu_width = dpi(140)
theme.menu_submenu_icon = theme.dir .. "/icons/submenu.png"
theme.awesome_icon = theme.dir .. "/icons/awesome.png"
theme.taglist_squares_sel = theme.dir .. "/icons/square_sel.png"
theme.taglist_squares_unsel = theme.dir .. "/icons/square_unsel.png"
theme.layout_tile = theme.dir .. "/icons/tile.png"
theme.layout_tileleft = theme.dir .. "/icons/tileleft.png"
theme.layout_tilebottom = theme.dir .. "/icons/tilebottom.png"
theme.layout_tiletop = theme.dir .. "/icons/tiletop.png"
theme.layout_fairv = theme.dir .. "/icons/fairv.png"
theme.layout_fairh = theme.dir .. "/icons/fairh.png"
theme.layout_spiral = theme.dir .. "/icons/spiral.png"
theme.layout_dwindle = theme.dir .. "/icons/dwindle.png"
theme.layout_max = default_theme_dir .. "layouts/max.png"
theme.layout_fullscreen = default_theme_dir .. "layouts/fullscreen.png"
theme.layout_magnifier = theme.dir .. "/icons/magnifier.png"
theme.layout_floating = theme.dir .. "/icons/floating.png"
theme.widget_ac = theme.dir .. "/icons/ac.png"
theme.widget_battery = theme.dir .. "/icons/battery.png"
theme.widget_battery_low = theme.dir .. "/icons/battery_low.png"
theme.widget_battery_empty = theme.dir .. "/icons/battery_empty.png"
theme.widget_brightness = theme.dir .. "/icons/brightness.png"
theme.widget_mem = theme.dir .. "/icons/mem.png"
theme.widget_cpu = theme.dir .. "/icons/cpu.png"
theme.widget_temp = theme.dir .. "/icons/temp.png"
theme.widget_net = theme.dir .. "/icons/net.png"
theme.widget_hdd = theme.dir .. "/icons/hdd.png"
theme.widget_music = theme.dir .. "/icons/note.png"
theme.widget_music_on = theme.dir .. "/icons/note_on.png"
theme.widget_music_pause = theme.dir .. "/icons/pause.png"
theme.widget_music_stop = theme.dir .. "/icons/stop.png"
theme.widget_vol = theme.dir .. "/icons/vol.png"
theme.widget_vol_low = theme.dir .. "/icons/vol_low.png"
theme.widget_vol_no = theme.dir .. "/icons/vol_no.png"
theme.widget_vol_mute = theme.dir .. "/icons/vol_mute.png"
theme.widget_mail = theme.dir .. "/icons/mail.png"
theme.widget_mail_on = theme.dir .. "/icons/mail_on.png"
theme.widget_task = theme.dir .. "/icons/task.png"
theme.widget_scissors = theme.dir .. "/icons/scissors.png"
theme.tasklist_plain_task_name = true
theme.tasklist_disable_icon = false
theme.useless_gap = 4
theme.titlebar_close_button_focus = theme.dir .. "/icons/titlebar/close_focus.png"
theme.titlebar_close_button_normal = theme.dir .. "/icons/titlebar/close_normal.png"
theme.titlebar_ontop_button_focus_active = theme.dir .. "/icons/titlebar/ontop_focus_active.png"
theme.titlebar_ontop_button_normal_active = theme.dir .. "/icons/titlebar/ontop_normal_active.png"
theme.titlebar_ontop_button_focus_inactive = theme.dir .. "/icons/titlebar/ontop_focus_inactive.png"
theme.titlebar_ontop_button_normal_inactive = theme.dir .. "/icons/titlebar/ontop_normal_inactive.png"
theme.titlebar_sticky_button_focus_active = theme.dir .. "/icons/titlebar/sticky_focus_active.png"
theme.titlebar_sticky_button_normal_active = theme.dir .. "/icons/titlebar/sticky_normal_active.png"
theme.titlebar_sticky_button_focus_inactive = theme.dir .. "/icons/titlebar/sticky_focus_inactive.png"
theme.titlebar_sticky_button_normal_inactive = theme.dir .. "/icons/titlebar/sticky_normal_inactive.png"
theme.titlebar_floating_button_focus_active = theme.dir .. "/icons/titlebar/floating_focus_active.png"
theme.titlebar_floating_button_normal_active = theme.dir .. "/icons/titlebar/floating_normal_active.png"
theme.titlebar_floating_button_focus_inactive = theme.dir .. "/icons/titlebar/floating_focus_inactive.png"
theme.titlebar_floating_button_normal_inactive = theme.dir .. "/icons/titlebar/floating_normal_inactive.png"
theme.titlebar_maximized_button_focus_active = theme.dir .. "/icons/titlebar/maximized_focus_active.png"
theme.titlebar_maximized_button_normal_active = theme.dir .. "/icons/titlebar/maximized_normal_active.png"
theme.titlebar_maximized_button_focus_inactive = theme.dir .. "/icons/titlebar/maximized_focus_inactive.png"
theme.titlebar_maximized_button_normal_inactive = theme.dir .. "/icons/titlebar/maximized_normal_inactive.png"
theme.icon_theme = "Numix"
local markup = lain.util.markup

-- Volume
local volumebar_widget = require("awesome-wm-widgets.volumebar-widget.volumebar")

-- Lain reports memory in MiB and network rates in KiB/s.
local function compact_value(value, small_unit, large_unit)
	value = tonumber(value) or 0
	if value >= 1024 then
		return string.format("%.1f%s", value / 1024, large_unit)
	end
	return string.format("%.0f%s", value, small_unit)
end

local function compact_rate(value)
	value = tonumber(value) or 0
	local unit = "K"
	if value >= 1024 * 1024 then
		value, unit = value / (1024 * 1024), "G"
	elseif value >= 1024 then
		value, unit = value / 1024, "M"
	end
	return string.format(value < 10 and unit ~= "K" and "%.1f%s" or "%.0f%s", value, unit)
end

local function build_screen_widgets(s)
	local widgets = {}

	widgets.clock = wibox.widget.textclock("<span font='Misc Tamsyn 5'> </span>%H:%M ")
	widgets.clock.font = theme.font

	widgets.cal = lain.widget.cal({
		attach_to = { widgets.clock },
		followtag = true,
		notification_preset = {
			font = theme.font,
			fg = theme.fg_normal,
			bg = theme.popup_bg,
			timeout = 0,
		},
	})

	local memicon = wibox.widget.imagebox(theme.widget_mem)
	widgets.mem = lain.widget.mem({
		settings = function()
			widget:set_markup(markup.font(theme.font, " " .. compact_value(mem_now.used, "M", "G") .. " "))
		end,
	})

	local cpuicon = wibox.widget.imagebox(theme.widget_cpu)
	widgets.cpu = lain.widget.cpu({
		settings = function()
			widget:set_markup(markup.font(theme.font, " " .. cpu_now.usage .. "% "))
		end,
	})

	local fsicon = wibox.widget.imagebox(theme.widget_hdd)
	widgets.fs = lain.widget.fs({
		followtag = true,
		notification_preset = {
			fg = theme.fg_normal,
			bg = theme.popup_bg,
			font = theme.font,
			border_width = 0,
			shape = theme.popup_shape,
		},
		settings = function()
			local root = fs_now["/"]
			if root then
				local fsp = string.format("%.1f%s", root.free, root.units)
				widget:set_markup(markup.font(theme.font, fsp))
			end
		end,
	})

	local baticon = wibox.widget.imagebox(theme.widget_battery)
	widgets.bat = lain.widget.bat({
		-- Refresh promptly on power changes instead of Lain's 30-second default.
		timeout = 2,
		notification_preset = { fg = theme.fg_normal, bg = theme.popup_bg, font = "Monospace 10" },
		settings = function()
			if bat_now.status and bat_now.status ~= "N/A" then
				if bat_now.ac_status == 1 then
					widget:set_markup(markup.font(theme.font, " AC "))
					baticon:set_image(theme.widget_ac)
					return
				elseif bat_now.perc and tonumber(bat_now.perc) <= 5 then
					baticon:set_image(theme.widget_battery_empty)
				elseif bat_now.perc and tonumber(bat_now.perc) <= 15 then
					baticon:set_image(theme.widget_battery_low)
				else
					baticon:set_image(theme.widget_battery)
				end
				widget:set_markup(markup.font(theme.font, " " .. bat_now.perc .. "% "))
			else
				widget:set_markup()
				baticon:set_image(theme.widget_ac)
			end
		end,
	})

	local neticon = wibox.widget.imagebox(theme.widget_net)
	widgets.net = lain.widget.net({
		screen = s,
		notification_preset = { fg = theme.fg_normal, bg = theme.popup_bg, font = "Monospace 10" },
		settings = function()
			widget:set_markup(
				markup.fontfg(
					theme.font,
					theme.titlebar_fg_focus,
					"↓" .. compact_rate(net_now.received)
						.. " ↑" .. compact_rate(net_now.sent)
					)
			)
		end,
	})
	-- Keep throughput updates from resizing the bar, without a wide empty slot.
	widgets.net.widget.forced_width = dpi(120)
	widgets.net.widget.align = "center"
	widgets.net.widget:connect_signal("mouse::enter", function()
		widgets.net_notification = naughty.notify({
			title = "Network",
			text = "Download / upload rate: K = KiB/s, M = MiB/s, G = GiB/s",
			screen = s,
			timeout = 0,
		})
	end)
	widgets.net.widget:connect_signal("mouse::leave", function()
		if widgets.net_notification then
			naughty.destroy(widgets.net_notification)
			widgets.net_notification = nil
		end
	end)

	widgets.volume = volumebar_widget({
		main_color = theme.bg_urgent,
		mute_color = "#777E7655",
		width = 80,
		shape = "rounded_bar",
		margins = 4,
		timeout = 2,
	})
	widgets.memicon = memicon
	widgets.cpuicon = cpuicon
	widgets.fsicon = fsicon
	widgets.baticon = baticon
	widgets.neticon = neticon

	return widgets
end

function theme.powerline_rl(cr, width, height)
	local arrow_depth, offset = height / 2, 0
	if arrow_depth < 0 then
		width = width + 2 * arrow_depth
		offset = -arrow_depth
	end
	-- Avoid going out of the (potential) clip area
	cr:move_to(offset + arrow_depth, 0)
	cr:line_to(offset + width, 0)
	cr:line_to(offset + width - arrow_depth, height / 2)
	cr:line_to(offset + width, height)
	cr:line_to(offset + arrow_depth, height)
	cr:line_to(offset, height / 2)

	cr:close_path()
end
local function pl(widget, bgcolor, padding)
	local horizontal_padding = dpi(padding or 10)
	return wibox.container.background(
		wibox.container.margin(widget, horizontal_padding, horizontal_padding), bgcolor, theme.powerline_rl
	)
end

function theme.at_screen_connect(s)
	-- Quake application
	s.quake = lain.util.quake({ app = awful.util.terminal })
	local widgets = build_screen_widgets(s)
	s.cal = widgets.cal
	s.fs = widgets.fs

	gears.wallpaper.maximized(theme.wallpaper_for(s), s, true)

	-- Tags
	awful.tag(awful.util.tagnames, s, awful.layout.layouts)
	s.tags[1].layout = lain.layout.centerwork
	s.tags[2].layout = awful.layout.suit.max
	s.tags[3].layout = awful.layout.suit.max
	-- Create a promptbox for each screen
	s.mypromptbox = awful.widget.prompt()
	-- Create an imagebox widget which will contains an icon indicating which layout we're using.
	-- We need one layoutbox per screen.
	s.mylayoutbox = awful.widget.layoutbox(s)
	s.mylayoutbox:buttons(my_table.join(
		awful.button({}, 1, function()
			awful.layout.inc(1)
		end),
		awful.button({}, 2, function()
			awful.layout.set(awful.layout.layouts[1])
		end),
		awful.button({}, 3, function()
			awful.layout.inc(-1)
		end),
		awful.button({}, 4, function()
			awful.layout.inc(1)
		end),
		awful.button({}, 5, function()
			awful.layout.inc(-1)
		end)
	))

	-- Create a taglist widget
	s.mytaglist = awful.widget.taglist(s, awful.widget.taglist.filter.all, awful.util.taglist_buttons)

	-- Create a tasklist widget
	s.mytasklist = awful.widget.tasklist(s, awful.widget.tasklist.filter.currenttags, awful.util.tasklist_buttons)

	-- Create the wibox
	s.mywibox =
		awful.wibar({ position = "top", screen = s, height = dpi(18), bg = theme.bg_normal, fg = theme.fg_normal })

	local left_widgets = {
		layout = wibox.layout.fixed.horizontal,
		--spr,
		s.mytaglist,
		s.mypromptbox,
		-- spr,
	}

	local right_widgets = {
		layout = wibox.layout.fixed.horizontal,
	}
	if s == screen.primary then
		table.insert(right_widgets, wibox.widget.systray())
	end

	-- generated by plugins/pluginctl; always exists, may be a no-op
	require("plugins")(left_widgets, right_widgets, pl, c, s)

	table.insert(right_widgets, pl(widgets.volume, c.widget_a .. "22"))
	table.insert(right_widgets, pl(wibox.widget({ widgets.memicon, widgets.mem.widget, layout = wibox.layout.align.horizontal }), c.widget_a .. "22"))
	table.insert(right_widgets, pl(wibox.widget({ widgets.cpuicon, widgets.cpu.widget, layout = wibox.layout.align.horizontal }), c.widget_b .. "22"))
	table.insert(right_widgets, pl(wibox.widget({ widgets.fsicon, widgets.fs.widget, layout = wibox.layout.align.horizontal }), c.widget_a .. "22"))
	table.insert(right_widgets, pl(wibox.widget({ widgets.baticon, widgets.bat.widget, layout = wibox.layout.align.horizontal }), c.widget_c .. "22"))
	table.insert(right_widgets, pl(wibox.widget({ widgets.neticon, widgets.net.widget, layout = wibox.layout.align.horizontal }), c.widget_b .. "22"))
	table.insert(right_widgets, power_mode.widget({}))
	table.insert(right_widgets, pl(widgets.clock, c.widget_a .. "22"))
	table.insert(right_widgets, logout.widget({}))
	table.insert(right_widgets, pl(s.mylayoutbox, ""))

	-- Add widgets to the wibox
	s.mywibox:setup({
		layout = wibox.layout.align.horizontal,
		left_widgets,
		s.mytasklist, -- Middle widget
		right_widgets,
	})
end

return theme
