#!/bin/zsh
# ═══════════════════════════════════════════════════════════════
# Powerlevel10k Instant Prompt (must stay at top)
# ═══════════════════════════════════════════════════════════════
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ═══════════════════════════════════════════════════════════════
# Shared Environment and PATH Defaults
# ═══════════════════════════════════════════════════════════════
# shellcheck source=../scripts/.config/shell/env.sh
source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"

# ═══════════════════════════════════════════════════════════════
# Plugins
# ═══════════════════════════════════════════════════════════════
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source "${XDG_CONFIG_HOME}/zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh"

# Powerlevel10k configuration
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Prompt colors generated by themectl. Re-source when the file changes so open
# shells follow a theme switch at their next prompt.
zmodload -F zsh/stat b:zstat 2>/dev/null
_p10k_theme_sync() {
  local f=~/.config/p10k-theme.zsh m
  [[ -r $f ]] || return
  zstat -A m +mtime -- $f 2>/dev/null || return
  [[ ${m[1]} == "$_p10k_theme_mtime" ]] && return
  local first=$_p10k_theme_mtime
  typeset -g _p10k_theme_mtime=${m[1]}
  source $f
  [[ -n $first ]] && (( $+functions[p10k] )) && p10k reload
}
_p10k_theme_sync
precmd_functions+=(_p10k_theme_sync)
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# ═══════════════════════════════════════════════════════════════
# Key Bindings
# ═══════════════════════════════════════════════════════════════
# Home key (go to beginning of line)
bindkey '^[[H' beginning-of-line
bindkey '^[OH' beginning-of-line  # For some terminals

# End key (go to end of line)
bindkey '^[[F' end-of-line
bindkey '^[OF' end-of-line        # For some terminals

# Ctrl + Left (backward-word)
bindkey '^[[1;5D' backward-word
bindkey '^[[5D' backward-word

# Ctrl + Right (forward-word)
bindkey '^[[1;5C' forward-word
bindkey '^[[5C' forward-word

# ═══════════════════════════════════════════════════════════════
# History
# ═══════════════════════════════════════════════════════════════
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# ═══════════════════════════════════════════════════════════════
# Completions
# ═══════════════════════════════════════════════════════════════
fpath=("${XDG_CONFIG_HOME}/zsh/completions" ${ASDF_DATA_DIR}/completions $fpath)
autoload -Uz compinit && compinit

# ═══════════════════════════════════════════════════════════════
# Source Config Files
# ═══════════════════════════════════════════════════════════════
source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/aliases.zsh"

# ═══════════════════════════════════════════════════════════════
# Dart CLI Completion (if installed)
# ═══════════════════════════════════════════════════════════════
[[ -f "$HOME/.config/.dart-cli-completion/zsh-config.zsh" ]] && \
  source "$HOME/.config/.dart-cli-completion/zsh-config.zsh"

# Railway CLI (if installed). The markers let its installer find this block.
# >>> railway initialize >>>
if [[ -f "$HOME/.railway/env" ]]; then source "$HOME/.railway/env"; fi
# <<< railway initialize <<<
