# Status: single color across the entire bar
set -g status-style ' fg=blue'
set -g window-status-separator ''

# Explicit colors everywhere (no defaults)
set -g status-left  '#[fg=green,bold] 󰕰 #S #[fg=white]  '
set -g status-right '#[fg=blue,bold]  #H#[fg=white]  #(whoami)'
set -g window-status-format          '#[fg=gray] #I:#W '
set -g window-status-current-format  '#[bold,fg=white] #I:#W '
